FROM nginx:1.15-alpine

WORKDIR /usr/share/nginx/html

COPY index.html index.html

# docker build .
# docker build - < Dockerfile
# docker image ls -a
# docker build . -t newname/nginx
# docker image rm d942d4a2f4fc
# docker image inspect dd23569e2efe
# docker container run -p 60:80 --name container1 -d 2a12a0effcb4
